CREATE DATABASE IF NOT EXISTS `$MYSQL_DATABASE`;

CREATE USER IF NOT EXISTS `$MYSQL_USER`@'*.srcs_inception' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON `$MYSQL_DATABASE`.* TO `$MYSQL_USER`@'*.srcs_inception' WITH GRANT OPTION;
ALTER USER '$MYSQL_USER'@'*.srcs_inception' IDENTIFIED BY '$MYSQL_PASSWORD';

CREATE USER IF NOT EXISTS '$MYSQL_ROOT_USER'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_ROOT_USER'@'%' WITH GRANT OPTION;
ALTER USER '$MYSQL_ROOT_USER'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';